const KEY='listrayl_chess_live_v5';
const SUPABASE_CONFIG={url:'https://dzqyfssxqxccunegsbxv.supabase.co',anonKey:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6cXlmc3N4cXhjY3VuZWdzYnh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkyOTUzMTEsImV4cCI6MjEwNDg3MTMxMX0.2vZngE9CFppBD6VQMf0ddygUgypO2c1E-f4Qud4IVeI'};
const MYTHICS={storm:{name:'Stormbringer',icon:'⚡',cost:500,desc:'Animated lightning aura.'},fire:{name:'Inferno Crown',icon:'🔥',cost:1000,desc:'Animated fire aura.'},void:{name:'Void Emperor',icon:'✦',cost:1800,desc:'Animated void aura.'}};
const BOARD_SKINS={classic:{name:'Classic Board',icon:'♟',cost:0,desc:'The standard tournament board.'},storm:{name:'Stormforge Board',icon:'⚡',cost:700,desc:'A blue mythic board forged for Stormbringer.'},fire:{name:'Inferno Board',icon:'🔥',cost:1200,desc:'A molten board for Inferno Crown.'},void:{name:'Void Board',icon:'✦',cost:2000,desc:'A dark mythic board for Void Emperor.'}};
const LEVELS=[['Rookie',0],['Bronze',100],['Silver',250],['Gold',600],['Diamond',1200],['Master',2500],['Grandmaster',5000]];
const RANK_BADGES={Rookie:'♙',Bronze:'♘',Silver:'♗',Gold:'♖',Diamond:'♕',Master:'♔',Grandmaster:'✦'};
function getAccount(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function defaults(name='Player'){return{name,uid:null,wins:0,losses:0,games:0,coins:0,xp:0,streak:0,bestStreak:0,inventory:['storm'],activeMythic:'storm',boardInventory:['classic'],activeBoard:'classic',history:[],achievements:[],missions:{},settings:{sound:true,animations:true,confirmMoves:false}}}
function saveAccount(a){localStorage.setItem(KEY,JSON.stringify(a));try{syncPlayer(a)}catch(e){console.warn('Player sync skipped',e)}}
async function startAccount(name){const n=String(name||'').trim().slice(0,20);if(!n)throw Error('Please enter a gaming name.');let a=getAccount()||defaults(n);a.name=n;a.inventory=Array.isArray(a.inventory)&&a.inventory.length?a.inventory:['storm'];a.activeMythic=a.activeMythic||'storm';localStorage.setItem(KEY,JSON.stringify(a));try{await syncPlayer(a)}catch(e){console.warn('Supabase sync skipped',e)}await new Promise(r=>setTimeout(r,50));location.replace('home.html');return true}
window.startAccount=startAccount;
function ensure(){if(!getAccount())location.href='index.html'}
function rank(a){let x=a?.xp||0;let r=LEVELS[0][0];for(const z of LEVELS)if(x>=z[1])r=z[0];return r}
function mythicIcon(kind){return MYTHICS[kind]?.icon||'⚡'}
function applyMythic(el,kind){el.className='mythic live '+(kind||'storm');el.textContent=mythicIcon(kind)}
function renderMythics(){const a=getAccount();document.querySelectorAll('[data-mythic]').forEach(e=>applyMythic(e,a?.activeMythic||'storm'))}
function renderHome(){const a=getAccount();homeName.textContent=a.name;homeRank.textContent=rank(a);homeCoins.textContent=a.coins;homeStats.innerHTML='<div class="stats section"><div class="stat"><div class="muted">WINS</div><div class="v">'+a.wins+'</div></div><div class="stat"><div class="muted">XP</div><div class="v">'+a.xp+'</div></div><div class="stat"><div class="muted">STREAK</div><div class="v">'+a.streak+'</div></div></div>';renderMythics()}
function renderProfile(){const a=getAccount();profileName.textContent=a.name;profileRank.textContent=rank(a)+' • '+a.xp+' XP';pw.textContent=a.wins;pl.textContent=a.losses;ps.textContent=a.streak;px.textContent=a.xp;pc.textContent=a.coins;pg.textContent=a.games;loadout.innerHTML=(a.inventory||[]).map(k=>'<div class="item"><span><b>'+MYTHICS[k].name+'</b><br><span class="muted">'+MYTHICS[k].desc+'</span></span><span class="badge">'+(a.activeMythic===k?'ACTIVE':'OWNED')+'</span></div>').join('');renderMythics()}
function renderLevels(){const a=getAccount();levelsList.innerHTML=LEVELS.map((z,i)=>{const next=LEVELS[i+1]?.[1]??z[1];const pct=i===LEVELS.length-1?100:Math.min(100,Math.max(0,(a.xp-z[1])/(next-z[1])*100));return '<div class="item"><span><b>'+z[0]+'</b><br><span class="muted">Requires '+z[1]+' XP</span><div class="progress"><i style="width:'+pct+'%"></i></div></span><span class="badge">'+(a.xp>=z[1]?'UNLOCKED':'LOCKED')+'</span></div>'}).join('')}
const PUZZLES=[['Mate pattern','Which move is strongest in a simple attack?',['Queen takes','Knight fork','Pawn push','King move'],1],['Fork tactic','Which piece commonly creates a fork?',['Knight','King','Pawn only','Rook only'],0],['Endgame','What should you prioritize?',['King activity','Random checks','Early queen trades always','Ignore pawns'],0]];
function renderPuzzle(){let i=Number(localStorage.getItem('listrayl_puzzle')||0)%PUZZLES.length,p=PUZZLES[i];puzzleCount.textContent='Puzzle '+(i+1)+' / '+PUZZLES.length;puzzleTitle.textContent=p[0];puzzleText.textContent=p[0]==='Mate pattern'?'Choose the tactical idea that wins material fastest.':p[0]==='Fork tactic'?'Pick the piece known for powerful forks.':'Pick the most useful endgame principle.';puzzleOptions.innerHTML=p[2].map((x,j)=>'<button class="btn puzzleOption" onclick="answerPuzzle('+j+','+p[3]+')">'+x+'</button>').join('');puzzleResult.classList.add('hidden')}
function answerPuzzle(j,correct){if(j!==correct){puzzleResult.className='result';puzzleResult.innerHTML='<b>Not quite.</b><p class="muted">Try the next puzzle after reviewing the idea.</p>';return}let a=getAccount();a.xp+=100;a.coins+=30;localStorage.setItem('listrayl_puzzle',String((Number(localStorage.getItem('listrayl_puzzle')||0)+1)%PUZZLES.length));addAchievement(a,'puzzle');saveAccount(a);puzzleResult.className='result win';puzzleResult.innerHTML='<div class="victoryBurst">✦</div><h2>PUZZLE SOLVED</h2><div class="reward">+100 XP · +30 COINS</div><button class="btn primary" onclick="renderPuzzle()">NEXT PUZZLE</button>'}
const ACH=[['first','First Victory','Win your first game',a=>a.wins>=1],['five','Five Wins','Win 5 games',a=>a.wins>=5],['streak','Hot Streak','Reach a 3-win streak',a=>a.bestStreak>=3],['mythic','Mythic Collector','Own all Mythic effects',a=>(a.inventory||[]).length>=3],['puzzle','Tactician','Solve a puzzle',a=>(a.achievements||[]).includes('puzzle')]];
function addAchievement(a,id){a.achievements=a.achievements||[];if(!a.achievements.includes(id))a.achievements.push(id)}
function renderAchievements(){const a=getAccount();ACH.forEach(x=>{if(x[3](a))addAchievement(a,x[0])});saveAccount(a);achievementsList.innerHTML=ACH.map(x=>'<div class="item"><span><b>'+x[1]+'</b><br><span class="muted">'+x[2]+'</span></span><span class="badge">'+(a.achievements.includes(x[0])?'UNLOCKED':'LOCKED')+'</span></div>').join('')}
function missionState(a,id){a.missions=a.missions||{};return a.missions[id]||{count:0,claimed:false}}
const MISS=[['wins','Win 3 games',3,150,()=>getAccount().wins],['play','Play 5 games',5,200,()=>getAccount().games],['puzzle','Solve 2 puzzles',2,250,()=>{let a=getAccount();return a.achievements?.includes('puzzle')?2:0}]];
function renderMissions(){const a=getAccount();missionsList.innerHTML=MISS.map(m=>{let s=missionState(a,m[0]),c=Math.min(m[2],m[4]());return '<div class="item"><span><b>'+m[1]+'</b><br><span class="muted">'+c+'/'+m[2]+' • Reward '+m[3]+' coins</span></span><button class="btn '+(c>=m[2]&&!s.claimed?'primary':'')+'" onclick="claimMission(\''+m[0]+'\')">'+(s.claimed?'CLAIMED':c>=m[2]?'CLAIM':'IN PROGRESS')+'</button></div>'}).join('')}
function claimMission(id){const m=MISS.find(x=>x[0]===id),a=getAccount(),s=missionState(a,id),c=m[4]();if(c<m[2]||s.claimed)return; s.claimed=true;a.missions[id]=s;a.coins+=m[3];saveAccount(a);renderMissions()}
function renderHistory(){const a=getAccount();historyList.innerHTML=(a.history||[]).length?a.history.slice().reverse().map(h=>'<div class="item"><span><b>'+h.mode.toUpperCase()+'</b><br><span class="muted">'+h.result+' • '+new Date(h.time).toLocaleString()+'</span></span><span class="badge">'+(h.result==='WIN'?'+150':'')+'</span></div>').join(''):'<p class="muted">No games yet. Play your first match.</p>'}
function renderShop(){const a=getAccount();shopCoins.textContent=a.coins;shopList.innerHTML='<div class="shopSectionTitle">MYTHIC EFFECTS</div>'+Object.entries(MYTHICS).map(([k,m])=>{let own=a.inventory?.includes(k);return '<div class="shopItem"><div class="shopIcon '+k+'">'+m.icon+'</div><b>'+m.name+'</b><p class="muted">'+m.desc+'</p><div class="row"><span class="badge">◈ '+m.cost+'</span><button class="btn '+(!own&&a.coins>=m.cost?'primary':'')+'" onclick="buyMythic(\''+k+'\')">'+(a.activeMythic===k?'ACTIVE':own?'EQUIP':'BUY')+'</button></div></div>'}).join('')+'<div class="shopSectionTitle">MYTHIC BOARDS</div>'+Object.entries(BOARD_SKINS).map(([k,m])=>{let own=a.boardInventory?.includes(k);return '<div class="shopItem"><div class="shopIcon board-'+k+'">'+m.icon+'</div><b>'+m.name+'</b><p class="muted">'+m.desc+'</p><div class="row"><span class="badge">'+(m.cost?'◈ '+m.cost:'FREE')+'</span><button class="btn '+(!own&&a.coins>=m.cost?'primary':'')+'" onclick="buyBoard(\''+k+'\')">'+(a.activeBoard===k?'ACTIVE':own?'EQUIP':'BUY')+'</button></div></div>'}).join('')}
function buyBoard(k){const a=getAccount(),m=BOARD_SKINS[k];a.boardInventory=a.boardInventory||['classic'];if(a.boardInventory.includes(k)){a.activeBoard=k;saveAccount(a);renderShop();drawSolo?.();drawMulti?.();return}if(a.coins<m.cost)return alert('Not enough coins');a.coins-=m.cost;a.boardInventory.push(k);a.activeBoard=k;saveAccount(a);renderShop();drawSolo?.();drawMulti?.();alert(m.name+' unlocked and equipped!')}
function buyMythic(k){const a=getAccount(),m=MYTHICS[k];if(a.inventory.includes(k)){a.activeMythic=k;saveAccount(a);renderShop();renderMythics();return}if(a.coins<m.cost)return alert('Not enough coins');a.coins-=m.cost;a.inventory.push(k);a.activeMythic=k;addAchievement(a,'mythic');saveAccount(a);renderShop();renderMythics();alert(m.name+' unlocked and equipped!')}
function renderSettings(){const a=getAccount();soundToggle.checked=a.settings?.sound!==false;animToggle.checked=a.settings?.animations!==false;confirmToggle.checked=!!a.settings?.confirmMoves}
function toggleSetting(k,v){const a=getAccount();a.settings=a.settings||{};a.settings[k]=v;saveAccount(a)}
function changeName(){const a=getAccount(),n=prompt('New gaming name',a.name);if(n&&n.trim()){a.name=n.trim().slice(0,20);saveAccount(a);location.reload()}}
function resetAccount(){if(!confirm('Reset this local account?'))return;localStorage.removeItem(KEY);location.href='index.html'}
function addHistory(a,mode,result,opponent='BOT'){a.history=a.history||[];a.history.push({mode,result,opponent,time:Date.now()});a.history=a.history.slice(-30)}
function updateAfterGame(win,mode,opponent='BOT'){const a=getAccount();a.games++;if(win){a.wins++;a.coins+=150;a.xp+=350;a.streak++;a.bestStreak=Math.max(a.bestStreak,a.streak)}else{a.losses++;a.xp+=50;a.streak=0}addHistory(a,mode,win?'WIN':'LOSS',opponent);if(a.wins>=1)addAchievement(a,'first');if(a.wins>=5)addAchievement(a,'five');if(a.bestStreak>=3)addAchievement(a,'streak');saveAccount(a);return a}
function supabaseReady(){return typeof window.supabase!=='undefined'&&SUPABASE_CONFIG.url&&!SUPABASE_CONFIG.url.startsWith('PASTE_')&&SUPABASE_CONFIG.anonKey&&!SUPABASE_CONFIG.anonKey.startsWith('PASTE_')}
let sb=null,authUid=null,authReady=false,roomChannel=null,leaderChannel=null;
async function sbStart(){if(!supabaseReady())return false;try{if(!sb)sb=window.supabase.createClient(SUPABASE_CONFIG.url,SUPABASE_CONFIG.anonKey);let {data:{session}}=await sb.auth.getSession();if(session?.user?.id){authUid=session.user.id;authReady=true;return true}try{const r=await sb.auth.signInAnonymously();if(!r.error&&r.data?.user?.id){authUid=r.data.user.id;authReady=true;return true}}catch(e){console.warn('Anonymous auth unavailable; using local player id',e)}authUid=localStorage.getItem('listrayl_supabase_uid')||crypto.randomUUID();localStorage.setItem('listrayl_supabase_uid',authUid);authReady=true;return true}catch(e){console.warn('Supabase start',e);return false}}
function playerData(a){return{id:authUid,name:a.name,wins:a.wins||0,losses:a.losses||0,games:a.games||0,coins:a.coins||0,xp:a.xp||0,rank:rank(a),streak:a.streak||0,best_streak:a.bestStreak||0,active_mythic:a.activeMythic||'storm',updated_at:new Date().toISOString()}}
async function syncPlayer(a){if(!supabaseReady())return;try{if(!(await sbStart()))return;const {error}=await sb.from('players').upsert(playerData(a),{onConflict:'id'});if(error)throw error}catch(e){console.warn('player sync',e)}}
async function loadLeaderboard(){
 const fallback=[{name:'@AddictedToBuhle',wins:100,xp:5000,rank:'Grandmaster',active_mythic:'storm'}];
 const renderFallback=()=>{leaderboardList.innerHTML=fallback.map((p,i)=>leaderRow(p,i)).join('');const total=document.getElementById('totalUsers');if(total)total.textContent='1'};
 if(!supabaseReady()){renderFallback();return}
 if(!(await sbStart())){renderFallback();return}
 const {data,error}=await sb.from('players').select('*').order('wins',{ascending:false}).order('xp',{ascending:false}).limit(10);
 const totalRes=await sb.from('players').select('id',{count:'exact',head:true});
 const total=document.getElementById('totalUsers');
 if(total)total.textContent=String(totalRes.count||0);
 if(error||!data?.length){renderFallback();if(total)total.textContent=String(totalRes.count||0);return}
 leaderboardList.innerHTML=data.slice(0,10).map((p,i)=>leaderRow(p,i)).join('');
}
function initLeaderboard(){loadLeaderboard().then(async()=>{if(!supabaseReady()||!await sbStart())return;if(leaderChannel)sb.removeChannel(leaderChannel);leaderChannel=sb.channel('leaderboard-live').on('postgres_changes',{event:'*',schema:'public',table:'players'},()=>loadLeaderboard()).subscribe()})}
function leaderRow(p,i){return '<div class="item"><span><b>#'+(i+1)+' '+String(p.name||'PLAYER').replace(/[<>]/g,'')+'</b><br><span class="muted">'+(p.rank||rank({xp:p.xp||0}))+' • '+(p.xp||0)+' XP</span></span><span class="badge">'+(p.wins||0)+' WINS</span></div>'}

// Solo engine

const CHESS_START=['rnbqkbnr','pppppppp','........','........','........','........','PPPPPPPP','RNBQKBNR'];const PIECES={w:{k:'♔',q:'♕',r:'♖',b:'♗',n:'♘',p:'♙'},b:{k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'}};let SB=[],SSEL=null,STURN='w',SOVER=false;
function newBoard(){return CHESS_START.map(r=>r.split('').map(c=>c==='.'?null:{c:c===c.toUpperCase()?'w':'b',p:c.toLowerCase()}))}
function inside(r,c){return r>=0&&r<8&&c>=0&&c<8}
function pieceMoves(B,r,c){const p=B[r][c],o=[],D=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];if(!p)return o;const add=(a,b)=>{if(!inside(a,b))return false;if(!B[a][b]){o.push([a,b]);return true}if(B[a][b].c!==p.c)o.push([a,b]);return false};if(p.p==='p'){const d=p.c==='w'?-1:1;if(inside(r+d,c)&&!B[r+d][c]){o.push([r+d,c]);if((p.c==='w'?r===6:r===1)&&!B[r+2*d][c])o.push([r+2*d,c])}for(const z of[-1,1])if(inside(r+d,c+z)&&B[r+d][c+z]&&B[r+d][c+z].c!==p.c)o.push([r+d,c+z])}if(p.p==='n')for(const z of[[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]])add(r+z[0],c+z[1]);if(p.p==='k')for(const z of D)add(r+z[0],c+z[1]);if(['b','r','q'].includes(p.p)){const ds=p.p==='b'?D.slice(4):p.p==='r'?D.slice(0,4):D;for(const z of ds){let a=r+z[0],b=c+z[1];while(inside(a,b)){if(!add(a,b))break;a+=z[0];b+=z[1]}}}return o}
function allMoves(B,color){const a=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(B[r][c]?.c===color)pieceMoves(B,r,c).forEach(x=>a.push([r,c,x[0],x[1]]));return a}
function legal(B,r,c,a,b){return pieceMoves(B,r,c).some(x=>x[0]===a&&x[1]===b)}
function drawSolo(){soloBoard.className='board theme-'+((getAccount()?.activeBoard)||'classic');soloBoard.innerHTML='';for(let r=0;r<8;r++)for(let c=0;c<8;c++){const e=document.createElement('div');e.className='sq '+((r+c)%2?'dark':'light');const p=SB[r][c];if(p)e.innerHTML='<span class="piece '+(p.c==='w'?'white3d':'black3d')+'">'+PIECES[p.c][p.p]+'</span>';if(SSEL&&SSEL[0]===r&&SSEL[1]===c)e.classList.add('sel');if(SSEL&&legal(SB,SSEL[0],SSEL[1],r,c)){e.classList.add('dot');if(SB[r][c])e.classList.add('capture')}e.onclick=()=>soloClick(r,c);soloBoard.appendChild(e)}soloStatus.textContent=SOVER?'Game over':STURN==='w'?'Your turn':'Bot thinking…'}
function soloClick(r,c){if(SOVER||STURN!=='w')return;if(SSEL){if(legal(SB,SSEL[0],SSEL[1],r,c)){doSoloMove([SSEL[0],SSEL[1],r,c]);SSEL=null;drawSolo();if(!SOVER)setTimeout(botMove,280)}else{SSEL=SB[r][c]?.c==='w'?[r,c]:null;drawSolo()}}else if(SB[r][c]?.c==='w'){SSEL=[r,c];drawSolo()}}
function doSoloMove(m){const[r,c,a,b]=m;SB[a][b]=SB[r][c];SB[r][c]=null;STURN=STURN==='w'?'b':'w';if(!allMoves(SB,STURN).length)finishSolo(STURN==='b');drawSolo()}
function botMove(){if(SOVER)return;const ms=allMoves(SB,'b');if(!ms.length){finishSolo(true);return}const vals={q:90,r:50,b:30,n:30,p:10,k:900};ms.sort((a,b)=>(SB[b[2]][b[3]]?vals[SB[b[2]][b[3]].p]:0)-(SB[a[2]][a[3]]?vals[SB[a[2]][a[3]].p]:0));doSoloMove(ms[Math.floor(Math.random()*Math.min(5,ms.length))])}
function finishSolo(win){if(SOVER)return;SOVER=true;const a=updateAfterGame(win,'solo','BOT');soloResult.className='result win';soloResult.innerHTML='<div class="victoryBurst">'+(win?'♛':'♟')+'</div><h2>'+ (win?'VICTORY!':'GAME OVER')+'</h2><p class="reward">'+(win?'+500 XP · +25 COINS':'+50 XP')+'</p><p class="muted">'+(win?'The board is yours. Mythic energy unlocked.':'Train again and come back stronger.')+'</p><button class="btn primary" onclick="newSoloGame()">PLAY AGAIN</button>';soloResult.classList.remove('hidden');drawSolo()}
function newSoloGame(){SB=newBoard();SSEL=null;STURN='w';SOVER=false;soloResult.className='result hidden';soloYou.textContent=getAccount().name;drawSolo()}
// Multiplayer — Supabase Realtime
let roomId=null,roomData=null,myColor=null,MB=[],MSEL=null,MOVER=false,roomResultHandled=false;
function roomPayload(){return{room_code:roomId,host_uid:authUid,white_uid:authUid,white_name:getAccount().name,white_rank:rank(getAccount()),black_uid:null,black_name:null,black_rank:null,board:MB,turn:'w',status:'waiting',winner:null,rewarded_by:{},created_at:new Date().toISOString()}}
async function createRoom(){
 if(!supabaseReady())return alert('Add your Supabase URL and anon key in app.js first.');
 if(!(await sbStart()))return alert('Supabase connection failed.');
 roomId=Math.random().toString(36).slice(2,8).toUpperCase();
 MB=newBoard();
 const payload=roomPayload();
 const {error}=await sb.from('rooms').insert(payload);
 if(error){
   console.error('create room',error);
   const msg=(error.message||error.code||'Supabase error');
   if(/black_name|schema cache|column .* does not exist/i.test(msg))return alert('Your rooms table is missing the latest columns. Run the updated supabase.sql, then refresh.');
   if(/row-level security|permission denied|policy/i.test(msg))return alert('Supabase RLS is blocking room creation. Run the updated supabase.sql policies.');
   return alert('Could not create room: '+msg);
 }
 roomInfo.innerHTML='<div class="room">'+roomId+'</div><p class="muted">Share this code with your opponent.</p>';
 listenRoom();
}
async function joinRoom(){if(!supabaseReady())return alert('Add your Supabase URL and anon key in app.js first.');if(!(await sbStart()))return alert('Supabase connection failed.');const id=(roomCodeInput.value||'').trim().toUpperCase();if(id.length!==6)return alert('Enter the 6-character room code.');roomId=id;const {data:d,error}=await sb.from('rooms').select('*').eq('room_code',roomId).maybeSingle();if(error||!d)return alert('Room not found.');if(d.black_uid)return alert('Room is full.');const {error:uerr}=await sb.from('rooms').update({black_uid:authUid,black_name:getAccount().name,black_rank:rank(getAccount()),status:'playing'}).eq('room_code',roomId);if(uerr)return alert('Could not join room.');listenRoom()}
async function fetchRoom(){const {data,error}=await sb.from('rooms').select('*').eq('room_code',roomId).maybeSingle();if(!error&&data)handleRoom(data)}
function handleRoom(d){roomData=d;if(!d)return;myColor=d.white_uid===authUid?'w':d.black_uid===authUid?'b':null;if(!myColor)return;try{MB=Array.isArray(d.board)?d.board:JSON.parse(d.board||'[]')}catch{MB=newBoard()}MOVER=d.status==='finished';lobby.classList.add('hidden');multiMatch.classList.remove('hidden');multiMe.innerHTML=(myColor==='w'?d.white_name:d.black_name)+' <span class="rankBadge">'+RANK_BADGES[(myColor==='w'?d.white_rank:d.black_rank)||'Rookie']+'</span>';multiOpp.innerHTML=(myColor==='w'?(d.black_name||'WAITING…'):d.white_name)+' <span class="rankBadge">'+RANK_BADGES[(myColor==='w'?d.black_rank:d.white_rank)||'Rookie']+'</span>';multiColor.textContent=myColor==='w'?'WHITE':'BLACK';multiOppColor.textContent=myColor==='w'?'BLACK':'WHITE';multiStatus.textContent=d.status==='waiting'?'Waiting for opponent…':MOVER?(d.winner===authUid?'VICTORY!':'GAME OVER'):d.turn===myColor?'Your turn':'Opponent turn';drawMulti();if(MOVER&&!roomResultHandled){roomResultHandled=true;if(d.winner===authUid){showMultiWin();if(!d.rewarded_by?.[authUid])finishMultiResult(true)}else if(d.winner){showMultiLoss();if(!d.rewarded_by?.[authUid])finishMultiResult(false)}}}
function listenRoom(){if(roomChannel)sb.removeChannel(roomChannel);roomResultHandled=false;fetchRoom();roomChannel=sb.channel('room-'+roomId).on('postgres_changes',{event:'*',schema:'public',table:'rooms',filter:'room_code=eq.'+roomId},payload=>handleRoom(payload.new)).subscribe()}
function drawMulti(){multiBoard.className='board theme-'+((getAccount()?.activeBoard)||'classic');multiBoard.innerHTML='';for(let r=0;r<8;r++)for(let c=0;c<8;c++){const e=document.createElement('div');e.className='sq '+((r+c)%2?'dark':'light');const p=MB[r][c];if(p)e.innerHTML='<span class="piece '+(p.c==='w'?'white3d':'black3d')+'">'+PIECES[p.c][p.p]+'</span>';if(MSEL&&MSEL[0]===r&&MSEL[1]===c)e.classList.add('sel');if(MSEL&&legal(MB,MSEL[0],MSEL[1],r,c)){e.classList.add('dot');if(MB[r][c])e.classList.add('capture')}e.onclick=()=>multiClick(r,c);multiBoard.appendChild(e)}}
async function multiClick(r,c){if(MOVER||!roomData||roomData.status!=='playing'||roomData.turn!==myColor)return;if(MSEL){if(legal(MB,MSEL[0],MSEL[1],r,c)){const n=MB.map(x=>x.slice());n[r][c]=n[MSEL[0]][MSEL[1]];n[MSEL[0]][MSEL[1]]=null;const next=myColor==='w'?'b':'w';MSEL=null;const winner=!n.some(row=>row.some(p=>p?.c===next));const patch={board:n,turn:next,status:winner?'finished':'playing',winner:winner?authUid:null};const {error}=await sb.from('rooms').update(patch).eq('room_code',roomId).eq('turn',myColor);if(error)console.warn('move',error)}else{MSEL=MB[r][c]?.c===myColor?[r,c]:null}drawMulti()}else if(MB[r][c]?.c===myColor){MSEL=[r,c];drawMulti()}}
async function finishMultiResult(win){const a=updateAfterGame(win,'multiplayer',myColor==='w'?roomData.black_name:roomData.white_name);const rewarded={...(roomData.rewarded_by||{}),[authUid]:true};await sb.from('rooms').update({rewarded_by:rewarded}).eq('room_code',roomId);roomData.rewarded_by=rewarded}
function showMultiWin(){multiResult.className='result win';multiResult.innerHTML='<div class="victoryBurst">♛</div><h2>VICTORY!</h2><p class="reward">+500 XP · +25 COINS</p>';multiResult.classList.remove('hidden')}
function showMultiLoss(){multiResult.className='result';multiResult.innerHTML='<div class="victoryBurst">♟</div><h2>GAME OVER</h2><p class="reward">+50 XP</p>';multiResult.classList.remove('hidden')}
function leaveRoom(){if(roomChannel&&sb){sb.removeChannel(roomChannel);roomChannel=null}roomData=null;roomId=null;MSEL=null;MOVER=false;roomResultHandled=false;multiMatch.classList.add('hidden');lobby.classList.remove('hidden');roomInfo.innerHTML=''}
function switchMode(mode){soloPanel.classList.toggle('hidden',mode!=='solo');multiPanel.classList.toggle('hidden',mode!=='multi');soloTab.classList.toggle('active',mode==='solo');multiTab.classList.toggle('active',mode==='multi');if(mode==='solo')newSoloGame()}
function initGamePage(){renderMythics();soloYou.textContent=getAccount().name;newSoloGame();const mode=new URLSearchParams(location.search).get('mode');if(mode==='multi')switchMode('multi')}
renderMythics();
